disabled_rules: # rule identifiers to exclude from running
  - line_length
  - file_length
  - variable_name
  - type_name
  - cyclomatic_complexity

type_name:
  max_length: # warning and error
    warning: 60
    error: 80

excluded: # paths to ignore during linting. Takes precedence over `included`.
  - Packages
  - Tests
