# docker-compose up
app:
  image: ibmcom/kitura-ubuntu:latest
  ports:
    - "8090:8090"
  volumes:
    - .:/root/cf-deployment-tracker-client-swift
  command: bash -c "make clean -C cf-deployment-tracker-client-swift && make -C cf-deployment-tracker-client-swift && make test -C cf-deployment-tracker-client-swift"